### ISSUE TITLE
Bad Arguments

### ISSUE THREAD

**Issue by philshil** [dpina000/nagios-eventhandler-cachet#1]
Hello,
sorry again just downloaded this version as i saw it had a couple of fixes, i have added in the api key and address and left everything else as it was before, nothing is happening again and just checked the logs and receive this in the logs
[1450796051] HOST EVENT HANDLER: test.curriculum.school;DOWN;SOFT;2;cachet_notify!Insight
[1450796051] wproc: HOST EVENTHANDLER job 1 from worker Core Worker 29088 is a non-check helper but exited with return code 1
[1450796051] wproc:   early_timeout=0; exited_ok=1; wait_status=256; error_code=0;
[1450796051] wproc:   stdout line 01: Bad arguments

**Comment by philshil** [comment]
(From cachet_notify)
#!/usr/bin/php
<?php

if ($argc != 6) {
        echo 'Usage: ' . basename(**FILE**) . ' cachet_component service_name service_state service_state_type service_output' . "\n";
        exit(1);
}

**Comment by dpina000** [comment]
@philshil 

Hi, did you use the master branch or the development branch, because my development branch is for testing so it's not advised to use this in production. If you're unsure then follow the original repo mpellegrin/nagios-eventhandler-cachet safely as that the most stable, and more people monitoring it and resolving issues.  

As for the error, can you try it manually to see what happens?
./cachet_notify 'Insight' 'My nagios service' CRITICAL SOFT 'The service is Critical'

Pls replace it with what your nagios is sending to be more accurate. Also, what version of cachet are you using? This was tested against release V2.0.0 and V2.0.3. 

Another test you can make is use the "debug" branch which uses the same features but adds verbosity to the console for troubleshooting issues.

**Comment by philshil** [comment]
Hello,
i just downloaded the zip copy from github so i would imagine the  master branch.
i can force it to command and it works. 
for some reason its working now automatically as well.. it has just created an incident and set my Internet service status to Major Outage which is one i just setup to test with. Just to let you know I'm  using version 2.0.0

**Comment by philshil** [comment]
is there a way to post to cachet when you acknowledge an issue on nagios?

**Comment by dpina000** [comment]
Run the manual command again and replace CRITICAL SOFT with OK HARD and it should clear the incident on cachet. If you have multiple incidents run it several times to close each incident. 

Also, you can close the incident from cachet itself, use the admin console and close any incidents as you need. Http://url/dashboard if you haven't used it yet.

Closing ticket now since it appears to be resolved on your end.
